version: "3"

# https://github.com/itzg/docker-minecraft-server
services:
  mc:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    environment:
      TYPE: "PAPER"
      VERSION: "1.19"
      MEMORY: "6G"
      MOTD: "Alex's Server"
      UID: "1001"
      EULA: "TRUE"
    volumes:
      - ./data:/data:Z
      - ./dynmap/:/var/opt/dynmap/web/:Z
    ports:
      - 25565:25565
    restart: on-failure

  dynmap:
    image: nginx:latest
    tty: true
    stdin_open: true
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - ./dynmap/:/var/opt/dynmap/web/:ro
      - ./nginx/:/etc/nginx/conf.d/:ro
      - /etc/ssl/alexjs.dev/:/etc/ssl/alexjs.dev/:ro
