version: "3"

# https://github.com/itzg/docker-minecraft-server
services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: mc
    tty: true
    stdin_open: true
    environment:
      TYPE: "PAPER"
      VERSION: "1.19"
      MEMORY: "6G"
      MOTD: "Alex's Server"
      EULA: "TRUE"
    volumes:
      - ./data:/data:Z
      - ./dynmap/:/usr/share/nginx/html/:z
    ports:
      - 25565:25565
    restart: on-failure

  dynmap:
    image: nginx:1.21-alpine
    container_name: map
    tty: true
    stdin_open: true
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
      NGINX_PORT: 443
      UID: "1000"
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - ./dynmap/:/usr/share/nginx/html/:z
      - ./nginx/:/etc/nginx/conf.d/:Z
      - /etc/ssl/alexjs.dev/:/etc/ssl/alexjs.dev/:Z
