version: "3"

# https://github.com/itzg/docker-minecraft-server
services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: mc
    tty: true
    stdin_open: true
    environment:
      TYPE: "PAPER"
      VERSION: "1.20.1"
      MEMORY: "6G"
      MOTD: "Alex's Server"
      EULA: "TRUE"
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
      - 8100:8100
    depends_on:
      - db
    restart: on-failure
    networks:
      - alexjs_network

  db:
    image: mariadb:10
    container_name: db
    tty: true
    stdin_open: true
    environment:
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql/
    restart: on-failure

networks:
  alexjs_network:
    external: true

volumes:
  db: {}
