version: "3"

# https://github.com/itzg/docker-minecraft-server
services:
  mc:
    image: itzg/minecraft-server:java17
    environment:
      TYPE: "PAPER"
      EULA: "TRUE"
      VERSION: "1.19"
    volumes:
      - ./data:/data:Z
    ports:
      - 25565:25565
    restart: unless-stopped
