version: "3"

# https://github.com/itzg/docker-minecraft-server
services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: mc
    tty: true
    stdin_open: true
    environment:
      TYPE: "PAPER"
      VERSION: "1.19"
      MEMORY: "6G"
      MOTD: "Alex's Server"
      EULA: "TRUE"
    volumes:
      - ./data:/data:Z
      - ./nginx/html/:/usr/share/nginx/html:z
    ports:
      - 25565:25565
    depends_on:
      - db
    restart: on-failure

  db:
    image: mariadb:10
    container_name: db
    tty: true
    stdin_open: true
    environment:
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - ./db/:/var/lib/mysql/:Z
    restart: on-failure

  dynmap:
    image: nginx:1.22-alpine
    container_name: map
    tty: true
    stdin_open: true
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
      NGINX_PORT: 443
      UID: "1000"
    ports:
      - 443:443
    depends_on:
      - db
    restart: on-failure
    volumes:
      - /etc/ssl/alexjs.dev/:/etc/ssl/alexjs.dev/:Z
      - ./nginx/conf.d/:/etc/nginx/conf.d/:Z
      - ./nginx/html/:/usr/share/nginx/html:z

volumes:
  db:
