version: "3"

# https://github.com/itzg/docker-minecraft-server
services:
  mc:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    environment:
      TYPE: "PAPER"
      VERSION: "1.19"
      MEMORY: "6G"
      EULA: "TRUE"
      UID: "1001"
    volumes:
      - ./data:/data:Z
    ports:
      - 25565:25565
    restart: unless-stopped
